
FROM python:3.9-slim


WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install required packages directly
RUN pip install --no-cache-dir Flask==2.3.2 mysql-connector-python==8.0.32 requests==2.31.0

# Expose the Flask app's port
EXPOSE 5000

# Set environment variables for Flask and MySQL connection


# Run the Flask application when the container launches
CMD ["python3", "raft-node.py"]
